CREATE STREAM INCOMING_OP_MSGS AS
SELECT jmsProperties->"JMSXGroupID"->"string" as "ORDER_ID",
jmsProperties->"TraceyId"->"string" as "TRACEY_ID",
text as "XML"
FROM STREAM_FROM_INCOMING_ACTIVEMQ WITH (VALUE_FORMAT='JSON') PARTITION BY ORDER_ID;