CREATE STREAM AUDIT WITH (PARTITIONS=4,REPLICAS=1,VALUE_FORMAT='JSON')
AS SELECT TRACEID as "TRACE_ID",
ROWKEY as "ORDER_ID",
TIMESTAMPTOSTRING(ROWTIME, 'yyyy-MM-dd HH:mm:ss.SSS') as "TIMESTAMP",
'ConvertedFromXmlToJson' as "EVENT",
'' as "ASSOCIATION"
FROM INSTRUCTIONS_STREAM_1;