CREATE STREAM STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
WITH (VALUE_FORMAT='JSON', PARTITIONS=4,REPLICAS=1) AS
SELECT o.TRACE_ID,
       o.OPERATOR_ID,
       o.ORDER_ID,
       o.SERVICE_ID,
       o.OPERATOR_ORDER_ID,
       o.DIRECTORY_NUMBER,
       v.switchServiceId as "SWITCH_SERVICE_ID",
       o.FEATURES
FROM STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN o
LEFT JOIN T_FROM_VOIP_SWITCH_SERVICES_PARTITIONED_FOR_JOIN v
ON o.SERVICE_ID = v.serviceId;
