CREATE STREAM STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN
WITH (VALUE_FORMAT='JSON', PARTITIONS=4,REPLICAS=1) AS
SELECT o.TRACE_ID,
       o.OPERATOR_ID,
       o.ORDER_ID,
       o.SERVICE_ID,
       o.OPERATOR_ORDER_ID,
       v.directoryNumber AS DIRECTORY_NUMBER,
       o.FEATURES
FROM REKEYED_RAW_VOIP_INSTRUCTIONS o
LEFT JOIN T_FROM_SERVICES_PARTITIONED_FOR_JOIN v
       ON o.SERVICE_ID = v.serviceId;
