CREATE STREAM AUDIT WITH (PARTITIONS=4,REPLICAS=3)
AS SELECT ROWKEY as "ORDER_ID",
ROWTIME as "TIMESTAMP",
'ConvertedFromXmlToJson' as "EVENT",
'' as "ASSOCIATION"
FROM INSTRUCTIONS_STREAM_1 WITH (VALUE_FORMAT='JSON');