INSERT into AUDIT
SELECT ROWKEY as "ORDER_ID",
ROWTIME as "TIMESTAMP",
'EnhancedWithSwitchServiceId' as "EVENT",
CAST (SWITCH_SERVICE_ID AS VARCHAR) as "ASSOCIATION"
FROM POST_SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID;
