INSERT into AUDIT
SELECT ROWKEY as "ORDER_ID",
TIMESTAMPTOSTRING(ROWTIME, 'yyyy-MM-dd HH:mm:ss.SSS') as "TIMESTAMP",
'ParsedJsonToModifyVoiceFeaturesMessage' as "EVENT",
'' as "ASSOCIATION"
FROM RAW_VOIP_INSTRUCTIONS;
