CREATE STREAM FROM_ENRICHED_MODIFICATION_INSTRUCTIONS_WITH_SERVICE (
    "OPERATORID" VARCHAR,
    "ORDERID" VARCHAR,
    "SERVICEID" VARCHAR,
    "DIRECTORYNUMBER" VARCHAR,
    "OPERATORORDERID" VARCHAR,
    "FEATURES" array<VARCHAR>)
WITH (KAFKA_TOPIC='enriched.modification.instructions.with.service', VALUE_FORMAT='JSON');