CREATE STREAM ENHANCED_VOIP_STREAM_3 AS
SELECT ENRICHEDINSTRUCTION->OPERATORID as operatorId,
       ENRICHEDINSTRUCTION->ORDERID as orderId,
       ENRICHEDINSTRUCTION->SERVICEID as serviceId,
       ENRICHEDINSTRUCTION->DIRECTORYNUMBER as directoryNumber,
       ENRICHEDINSTRUCTION->OPERATORORDERID as operatorOrderId,
       ENRICHEDINSTRUCTION->FEATURES as features
FROM ENRICHED_MODIFICATION_INSTRUCTIONS_WITH_SERVICE
PARTITION by serviceId;
